const express = require('express');
const router = express.Router();
const Vehicle = require('../models/Vehicle'); //
const Booking = require('../models/Booking'); //
const User = require('../models/user'); // Import User model
const { upload } = require('../middleware/auth');


// POST /api/vehicles/list (Upload a new vehicle with photos)

router.post('/list', upload.fields([
    { name: 'photos', maxCount: 6 },
    { name: 'document_front', maxCount: 1 },
    { name: 'document_back', maxCount: 1 }
]), async (req, res) => {
    try {
        const {
            vendor_id, vendor_email, make, model_year, registration_no,
            registration_date, owner_name, tax_payment, address, price_per_day, category,
            lat, lng, driver_price_per_day, hourly_rate, minimum_hours, allow_hourly_rentals,
            operating_hours_start, operating_hours_end
        } = req.body;

        // BAN CHECK: Prevent banned vendors from listing vehicles.
        const vendor = await User.findById(vendor_id);
        if (!vendor || vendor.status === 'banned') {
            return res.status(403).json({ msg: 'Your account is suspended. You cannot list new vehicles.' });
        }

        // Save file paths generated by Multer
        const photos = req.files && req.files['photos'] ? req.files['photos'].map(file => file.path) : [];
        const document_front = req.files && req.files['document_front'] ? req.files['document_front'][0].path : null;
        const document_back = req.files && req.files['document_back'] ? req.files['document_back'][0].path : null;

        const newVehicle = new Vehicle({
            vendor_id, vendor_email, make, model_year, registration_no, registration_date, owner_name, tax_payment, address, category,
            price_per_day: Number(price_per_day) || 0, 
            lat: Number(lat) || 0, 
            lng: Number(lng) || 0, 
            hourly_rate: Number(hourly_rate) || 0,
            minimum_hours: Number(minimum_hours) || 1,
            allow_hourly_rentals: allow_hourly_rentals === 'true',
            operating_hours_start: operating_hours_start || '09:00',
            operating_hours_end: operating_hours_end || '21:00',
            driver_price_per_day: Number(driver_price_per_day) || 0,
            photos,
            document_front,
            document_back,
            status: 'active' // Marking as active so it instantly appears
        });

        await newVehicle.save();
        res.status(201).json({ msg: 'Vehicle listed successfully!', vehicle: newVehicle });
    } catch (err) {
        res.status(500).json({ msg: 'Failed to list vehicle.', error: err.message });
    }
});

// ================================================================
// GET /api/vehicles/all (Pulls all available vehicles for browsing/features)
// ================================================================
router.get('/all', async (req, res) => {
    try {
        const query = { status: 'active' };
        
        // Add search functionality for car name, make, or model
        if (req.query.search) {
            const escapedSearch = req.query.search.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
            const searchRegex = new RegExp(escapedSearch, 'i');
            query.$or = [
                { make: searchRegex },
                { model_year: searchRegex },
                { owner_name: searchRegex }
            ];
        }

        const vehicles = await Vehicle.find(query)
            .populate('vendor_id', 'full_name vendor_address')
            .sort({ createdAt: -1 });

        const outputVehicles = await Promise.all(vehicles.map(async (v) => {
            const activeBooking = await Booking.findOne({
                vehicle: v._id,
                status: { $in: ['confirmed', 'active'] }
            });
            
            const carObj = v.toObject();
            carObj.is_available = !activeBooking;
            return carObj;
        }));

        res.status(200).json({ vehicles: outputVehicles });
    } catch (err) {
        res.status(500).json({ msg: 'Error fetching all vehicles.', error: err.message });
    }
});

// ================================================================
// GET /api/vehicles/vendor/:vendor_id (Pulls all cars for a specific vendor showroom)
// ================================================================
router.get('/vendor/:vendor_id', async (req, res) => {
    try {
        const vehicles = await Vehicle.find({ vendor_id: req.params.vendor_id })
            .populate('vendor_id', 'full_name vendor_address')
            .sort({ createdAt: -1 });
        
        // Dynamic Availability Filter: Exclude vehicles with active bookings
        const outputVehicles = await Promise.all(vehicles.map(async (v) => {
            const activeBooking = await Booking.findOne({
                vehicle: v._id,
                status: { $in: ['confirmed', 'active'] }
            });
            
            const carObj = v.toObject();
            // If booked or marked manually inactive, set available status flags to false
            carObj.is_available = !activeBooking && carObj.status === 'active';
            return carObj;
        }));

        res.status(200).json({ vehicles: outputVehicles });
    } catch (err) {
        res.status(500).json({ msg: 'Error fetching vendor fleet data.', error: err.message });
    }
});

// ================================================================
// GET /api/vehicles/:vehicleId (Pulls a single car for editing/details)
// This must come before other routes that also use a vehicleId parameter.
// ================================================================



router.get('/:vehicleId', async (req, res) => {
    try {
        const vehicle = await Vehicle.findById(req.params.vehicleId)
            .populate('vendor_id'); // Populate the full vendor object
        if (!vehicle) {
            return res.status(404).json({ msg: 'Vehicle not found.' });
        }
        res.status(200).json({ vehicle });
    } catch (err) {
        res.status(500).json({ msg: 'Error fetching vehicle details.', error: err.message });
    }
});

// ================================================================
// PATCH /api/vehicles/:vehicleId/toggle-status (Allows vendors to manual block a car)
// ================================================================
router.patch('/:vehicleId/toggle-status', async (req, res) => {
    try {
        const vehicle = await Vehicle.findById(req.params.vehicleId);
        if (!vehicle) return res.status(404).json({ error: 'Vehicle missing.' });

        // Prevent vendor from changing a suspended status
        if (vehicle.status === 'suspended') {
            return res.status(403).json({ error: 'This vehicle is suspended by an admin and cannot be modified.' });
        }

        // Vendor can only toggle between 'active' and 'inactive'
        vehicle.status = vehicle.status === 'active' ? 'inactive' : 'active';
        await vehicle.save();

        res.status(200).json({ success: true, status: vehicle.status });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// ================================================================
// PATCH /api/vehicles/:vehicleId/edit (Allows vendors to edit photos)
// ================================================================
router.patch('/:vehicleId/edit', upload.fields([
    { name: 'photos', maxCount: 6 }
]), async (req, res) => {
    try {
        const { vehicleId } = req.params;
        const {
            existingPhotos, driver_price_per_day, with_petrol, hourly_rate,
            allow_hourly_rentals, minimum_hours, price_per_day,
            operating_hours_start, operating_hours_end
        } = req.body;

        const vehicle = await Vehicle.findById(vehicleId);
        if (!vehicle) return res.status(404).json({ msg: 'Vehicle not found.' });

        // Photo management
        let photosToKeep = [];
        if (existingPhotos) {
            photosToKeep = Array.isArray(existingPhotos) ? existingPhotos : [existingPhotos];
        }
        const newPhotos = req.files?.['photos'] ? req.files['photos'].map(f => f.path) : [];
        const updatedPhotos = [...photosToKeep, ...newPhotos];
        if (updatedPhotos.length > 6) return res.status(400).json({ msg: 'Max 6 photos allowed.' });

        const updateFields = {
            photos: updatedPhotos,
            driver_price_per_day: Number(driver_price_per_day) || 0,
            with_petrol: with_petrol === 'true' || with_petrol === true,
            price_per_day: Number(price_per_day) || vehicle.price_per_day || 0,
            hourly_rate: Number(hourly_rate) || 0,
            allow_hourly_rentals: allow_hourly_rentals === 'true' || allow_hourly_rentals === true,
            minimum_hours: Number(minimum_hours) || 1,
            operating_hours_start: operating_hours_start || '09:00',
            operating_hours_end: operating_hours_end || '21:00',
        };

        const updated = await Vehicle.findByIdAndUpdate(
            vehicleId,
            { $set: updateFields },
            { new: true, strict: false }
        );

        res.status(200).json({ msg: 'Vehicle updated successfully!', vehicle: updated });
    } catch (err) {
        res.status(500).json({ msg: 'Error updating vehicle.', error: err.message });
    }
});

// ================================================================
// DELETE /api/vehicles/:vehicleId (Allows a vendor to delete their vehicle)
// ================================================================
router.delete('/:vehicleId', async (req, res) => {
    try {
        const { vehicleId } = req.params;

        const vehicle = await Vehicle.findById(vehicleId);
        if (!vehicle) {
            return res.status(404).json({ msg: 'Vehicle not found.' });
        }

        // Prevent deletion if there are active or upcoming bookings
        const activeBooking = await Booking.findOne({
            vehicle: vehicleId,
            status: { $in: ['confirmed', 'active'] }
        });

        if (activeBooking) {
            return res.status(400).json({ msg: 'Cannot delete vehicle with active or upcoming bookings. Please handle them first.' });
        }

        await Vehicle.findByIdAndDelete(vehicleId);
        res.status(200).json({ msg: 'Vehicle has been permanently deleted.' });
    } catch (err) {
        res.status(500).json({ msg: 'Error deleting vehicle.', error: err.message });
    }
});

module.exports = router;