const express = require('express');
const router = express.Router();
const Vehicle = require('../models/Vehicle'); //
const Booking = require('../models/Booking'); //
const { upload } = require('../middleware/auth');

// ================================================================
// POST /api/vehicles/list (Upload a new vehicle with photos)
// ================================================================
router.post('/list', upload.fields([
    { name: 'photos', maxCount: 6 },
    { name: 'document_front', maxCount: 1 },
    { name: 'document_back', maxCount: 1 }
]), async (req, res) => {
    try {
        const {
            vendor_id, vendor_email, make, model_year, registration_no,
            registration_date, owner_name, tax_payment, address,
            price_per_day, category, lat, lng
        } = req.body;

        // Save file paths generated by Multer
        const photos = req.files && req.files['photos'] ? req.files['photos'].map(file => file.path) : [];
        const document_front = req.files && req.files['document_front'] ? req.files['document_front'][0].path : null;
        const document_back = req.files && req.files['document_back'] ? req.files['document_back'][0].path : null;

        const newVehicle = new Vehicle({
            vendor_id, vendor_email, make, model_year, registration_no,
            registration_date, owner_name, tax_payment, address,
            price_per_day, category, lat, lng,
            photos,
            document_front,
            document_back,
            status: 'active' // Marking as active so it instantly appears
        });

        await newVehicle.save();
        res.status(201).json({ msg: 'Vehicle listed successfully!', vehicle: newVehicle });
    } catch (err) {
        res.status(500).json({ msg: 'Failed to list vehicle.', error: err.message });
    }
});

// ================================================================
// GET /api/vehicles/vendor/:vendor_id (Pulls all cars for a specific vendor showroom)
// ================================================================
router.get('/vendor/:vendor_id', async (req, res) => {
    try {
        const vehicles = await Vehicle.find({ vendor_id: req.params.vendor_id }).sort({ createdAt: -1 });
        
        // Dynamic Availability Filter: Exclude vehicles with active bookings
        const outputVehicles = await Promise.all(vehicles.map(async (v) => {
            const activeBooking = await Booking.findOne({
                vehicle: v._id,
                status: { $in: ['confirmed', 'active'] }
            });
            
            const carObj = v.toObject();
            // If booked or marked manually inactive, set available status flags to false
            carObj.is_available = !activeBooking && carObj.status === 'active';
            return carObj;
        }));

        res.status(200).json({ vehicles: outputVehicles });
    } catch (err) {
        res.status(500).json({ msg: 'Error fetching vendor fleet data.', error: err.message });
    }
});

// ================================================================
// GET /api/vehicles/all (Pulls all available vehicles for browsing/features)
// ================================================================
router.get('/all', async (req, res) => {
    try {
        const query = { status: 'active' };
        
        // Add search functionality for car name, make, or model
        if (req.query.search) {
            const searchRegex = new RegExp(req.query.search, 'i'); // 'i' makes it case-insensitive
            query.$or = [
                { name: searchRegex },
                { make: searchRegex },
                { model: searchRegex }
            ];
        }

        const vehicles = await Vehicle.find(query)
            .populate('vendor_id', 'full_name vendor_address')
            .sort({ createdAt: -1 });

        const outputVehicles = await Promise.all(vehicles.map(async (v) => {
            const activeBooking = await Booking.findOne({
                vehicle: v._id,
                status: { $in: ['confirmed', 'active'] }
            });
            
            const carObj = v.toObject();
            carObj.is_available = !activeBooking;
            return carObj;
        }));

        res.status(200).json({ vehicles: outputVehicles });
    } catch (err) {
        res.status(500).json({ msg: 'Error fetching all vehicles.', error: err.message });
    }
});
// ================================================================
// PATCH /api/vehicles/:vehicleId/toggle-status (Allows vendors to manual block a car)
// ================================================================
router.patch('/:vehicleId/toggle-status', async (req, res) => {
    try {
        const vehicle = await Vehicle.findById(req.params.vehicleId);
        if (!vehicle) return res.status(404).json({ error: 'Vehicle missing.' });

        // Toggle listing status between active and inactive
        vehicle.status = vehicle.status === 'active' ? 'inactive' : 'active';
        await vehicle.save();

        res.status(200).json({ success: true, status: vehicle.status });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

module.exports = router;